#! /bin/bash
exec 2>&1

export JAVA_HOME="{{pkgPathFor "core/openjdk11"}}"
export ZOOMAIN=org.apache.zookeeper.server.quorum.QuorumPeerMain
export ZOOCFGDIR=/etc/zookeeper/conf
export ZOOCFG=/etc/zookeeper/conf/zoo.cfg
export ZOO_LOG_DIR=/var/log/zookeeper
export ZOO_LOG4J_PROP=INFO,ROLLINGFILE
export JMXLOCALONLY=true
exec {{pkg.path}}/bin/zkServer.sh start /etc/zookeeper/conf/zoo.cfg
